version: '2'

services:
    db:
        build: phoenix_db
        ports:
            - 5432:5432
        volumes:
            - "./.data/db:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: phoenix
    phoenix:
        build: phoenix
        command: mix phoenix.server
        ports:
            - 4000:4000
        links:
            - db:postgres
        volumes:
            - /home/luca/Documents/ruru:/app
