version: '2'

services:
    db:
        build: phoenix_db
        ports:
            - 5432:5432
        volumes:
            - "./.data/db:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: phoenix
    rethinkdb:
       image: rethinkdb
       ports:
            - 28015:28015
            - 8080:8080
       volumes:
            - "./.data/rethinkdb:/data"
    phoenix:
        build: phoenix
        command: mix phoenix.server
        ports:
            - 4000:4000
        links:
            - db:postgres
            - rethinkdb:rethinkdb
        volumes:
            - /home/luca/Documents/ruru:/app
